# Generated by Django 6.1.1 on 2026-10-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='section',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
