# Generated by Django 6.1.1 on 2026-10-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_students_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='codename',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
